from pathlib import Path
import re,html,json
p=Path('index.html'); old=p.read_text(encoding='utf-8')
projects=[]
for a in re.findall(r'<article\b.*?</article>',old,re.S):
 def get(pattern): return html.unescape(re.sub(r'\s+',' ',re.search(pattern,a,re.S).group(1)).strip())
 projects.append(dict(category=get(r'data-category="(.*?)"'),href=get(r'href="(.*?)"'),title=get(r'<h3[^>]*>(.*?)</h3>'),description=get(r'<p[^>]*>(.*?)</p>')))
for x in projects:
 if '3D_minesweeper' in x['href']: x['href']='game/3D_%20minesweeper/index.html'
Path('work/original-projects.json').write_text(json.dumps(projects,ensure_ascii=False),encoding='utf-8')
art=['<div class="food">on<span>sic.</span></div>','<div class="cube-grid">'+''.join('<i></i>' for _ in range(9))+'</div>','<div class="slime"><i></i><i></i></div>','<div class="orbit"><i></i><b></b></div>','<div class="maze">'+''.join('<i></i>' for _ in range(25))+'</div>','<div class="terminal">&gt; access_lab<br><span>ACCESS GRANTED_</span></div>','<div class="shadow-block"></div>','<div class="cube-grid">'+''.join('<i>'+str(i%3+1)+'</i>' for i in range(9))+'</div>','<div class="hell">SIGN UP<span>if you can.</span></div>','<div class="circle-art"></div>','<div class="captcha"><i>✓</i> I’m not a robot<span>…or am I?</span></div>']
colors=['rose','mint','lime','violet','sand','mint','violet','blue','rose','sand','blue']
cards=''
for i,x in enumerate(projects):
 external=' target="_blank" rel="noopener noreferrer"' if x['href'].startswith('http') else ''
 cards+=f'''<article class="project-item" data-category="{x['category']}"><a class="project-card" href="{html.escape(x['href'],quote=True)}"{external}><div class="art {colors[i]}" aria-hidden="true"><span class="art-index">EXPERIMENT / {i+1:02}</span>{art[i]}<span class="open-project">↗</span></div><div class="card-meta"><span>{x['category'].upper()}</span><span>{i+1:02} / 11</span></div><h3>{x['title']}</h3><p>{x['description']}</p></a></article>'''
head=old[:old.index('    <script src="https://cdn.tailwindcss.com">')]
head+='''    <meta name="description" content="승민의 크리에이티브 코딩 실험실. 웹 게임, 모바일 앱, 그리고 호기심에서 시작된 인터랙티브 실험들."><link rel="stylesheet" href="home.css"><script defer src="home.js"></script></head>'''
body='''<body><a class="skip-link" href="#projects">프로젝트 바로가기</a><div class="page-shell"><header><a class="wordmark" href="./" aria-label="승민의 실험실 홈">s<span class="brand-star">✳</span>lab<span class="brand-dot">.</span></a><nav aria-label="메인 메뉴"><a href="#projects">Experiments <sup>11</sup></a><a href="#about">About</a></nav><button id="sfx-toggle-btn" aria-label="사운드 효과 켜기" aria-pressed="false"><span class="sound-bars" aria-hidden="true">▂▅▃▆</span><span id="sfx-label">Sound off</span></button></header><main><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> SEUNGMIN’S CREATIVE CODING LAB</p><h1 id="hero-title">Small ideas.<br>Limitless <em>play.</em></h1><div class="hero-bottom"><p>호기심을 코드로, 상상을 플레이로.<br>직접 만지고 즐기는 승민의 작은 실험들.</p><a class="round-link" href="#projects" aria-label="실험 살펴보기">↓</a></div></div><div class="hero-art" aria-hidden="true"><div class="orbital"><div class="orbital-ring ring-one"></div><div class="orbital-ring ring-two"></div><div class="orbital-ring ring-three"></div><div class="orbital-core"></div><span class="satellite"></span></div><span class="art-coordinate">FIG. 001 — CURIOSITY IN MOTION</span><span class="art-plus">+</span></div></section><div class="ticker" aria-hidden="true"><div>IDEAS INTO INTERACTION <span>✳</span> MADE TO BE PLAYED <span>✳</span> ALWAYS EXPERIMENTING <span>✳</span> IDEAS INTO INTERACTION <span>✳</span> MADE TO BE PLAYED <span>✳</span> ALWAYS EXPERIMENTING <span>✳</span></div></div><section id="projects" class="projects" aria-labelledby="projects-title"><div class="section-heading"><div><p class="eyebrow">THE EXPERIMENT INDEX</p><h2 id="projects-title">골라서, 플레이.<span>↘</span></h2></div><p>작은 화면 속, 새로운 경험.</p></div><div class="filter-bar" aria-label="프로젝트 카테고리 필터"><div class="filters">'''
for key,label in [('all','전체'),('app','모바일 앱'),('game','웹 게임'),('lab','밈 & 실험실')]:
 count=len(projects) if key=='all' else sum(x['category']==key for x in projects)
 body+=f'<button class="tab-btn {"active" if key=="all" else ""}" data-filter="{key}" aria-pressed="{"true" if key=="all" else "false"}">{label} <span id="count-{key}">{count:02}</span></button>'
body+='''</div><span id="result-count" aria-live="polite">11 experiments</span></div><div class="project-grid">'''+cards+'''</div><p id="empty-state" hidden>아직 등록된 실험이 없습니다.</p></section><section id="about" class="about" aria-label="About Me 프로필"><span class="about-star" aria-hidden="true">✳</span><div><p class="eyebrow">THE PERSON BEHIND THE PLAY</p><h2>안녕하세요, 승민입니다.</h2><p>아이디어를 직접 만들고, 움직이고, 플레이해 봅니다.<br>이곳은 그 과정에서 태어난 프로젝트들을 모아 둔 실험실입니다.</p><div class="tech-stack">JavaScript · HTML5 · CSS3 · Three.js · WebGL · Canvas · Android</div></div><a href="https://github.com/seuuung" target="_blank" rel="noopener noreferrer">GitHub 프로필 ↗</a></section></main><footer><a class="wordmark" href="./">s✳lab.</a><span>© <span id="year">2026</span> Seungmin · Built with curiosity.</span><a href="#">Back to top ↑</a></footer></div></body></html>'''
p.write_text(head+body,encoding='utf-8')
print('Rebuilt homepage with',len(projects),'preserved projects')
